version: '3.8'
services:
  api:
    depends_on:
      - kafka
      - keycloak
    container_name: "hrm_api_${NODE_ENV}"
    image: "hrm_api_${NODE_ENV}"
    environment:
      NODE_ENV: ${NODE_ENV}
      API_KAKFA_CONNECT: kafka:9092
    build:
      context: ./
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    ports:
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - kafka-net

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports: 
      - "8080:8080"
    environment: 
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'
      - 'KEYCLOAK_IMPORT=/tmp/realm-export.json'
      - 'DB_VENDOR=h2'
    volumes: 
      - ./tmp/realm-export.json:/tmp/realm-export.json

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-net
networks:
  kafka-net: