version: '3.8'
services:
  api:
    depends_on:
      - kafka
      - keycloak
    container_name: "frontend_api_${NODE_ENV}"
    image: "frontend_api_${NODE_ENV}"
    environment:
      NODE_ENV: ${NODE_ENV}
      KAKFA_API_CONNECT: kafka_sad:9092
      KEYCLOAK_API_CONNECT: keycloak_sad:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_ID: api-client
      KEYCLOAK_SECRET: b500edae-a51a-461e-9672-dab78d694ecb
    build:
      context: ./frontend/
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  keycloak:
    container_name: "keycloak_sad"
    depends_on:
      - kafka
    image: quay.io/keycloak/keycloak:20.0.1
    command: 'start-dev'
    ports: 
      - "8080:8080"
    environment: 
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
      - 'KEYCLOAK_IMPORT=/tmp/realm-export.json'
      - 'DB_VENDOR=h2'
    volumes: 
      - ./tmp/realm-export.json:/tmp/realm-export.json

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  
  kafka:
    container_name: "kafka_sad"
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - 9092:9092
      - 9094:9094
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test,test_response"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default: 
    name: sad-net